import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="m-4">
        <div className="flex justify-between ">
            <h1 className="text-lg">Shuttle AI</h1>
            <p className="text-sm text-gray-500 my-1">
              badminton performance tracker
            </p>
          </div>
          </main>
          <hr className="border-t border-gray-400 my-4 w-full" />
        {children}
        </body>
    </html>
  );
}
